apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
 name: jgonzalezagu-zant
 namespace: nsdemo2
spec:
 distribution:
   fullVersion: ""
   #version: v1.19.7 # to upgrade to
   version: v1.18.15 # original
 topology:
   controlPlane:
     count: 1
     class: guaranteed-xsmall
     storageClass: tanzu
   workers:
     count: 1
     class: guaranteed-xsmall
     storageClass: tanzu
 settings:
   network:
     cni:
       name: antrea
     services:
       cidrBlocks: ["198.51.100.0/12"] #Cannot overlap with Supervisor Cluster
     pods:
       cidrBlocks: ["192.0.2.0/16"] #Cannot overlap with Supervisor Cluster
   storage:
     defaultClass: tanzu
