apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
 name: jgonzalezagu-ghirahim
 namespace: nsdemo2
spec:
 distribution:
   fullVersion: null
   version: v1.18.15
 topology:
   controlPlane:
     count: 1
     class: guaranteed-xsmall
     storageClass: pacific-gold-storage-policy
   workers:
     count: 2
     class: guaranteed-xsmall
     storageClass: pacific-gold-storage-policy
 settings:
   network:
     cni:
       name: calico
     services:
       cidrBlocks: ["198.51.100.0/12"] #Cannot overlap with Supervisor Cluster
     pods:
       cidrBlocks: ["192.0.2.0/16"] #Cannot overlap with Supervisor Cluster
   storage:
     defaultClass: pacific-gold-storage-policy
