apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
 name: jgonzalezagu-onox
 namespace: nsdemo1
spec:
 distribution:
   version: v1.19.7
 topology:
   controlPlane:
     count: 1
     class: best-effort-xsmall
     storageClass: tanzu
   workers:
     count: 1
     class: best-effort-xsmall
     storageClass: tanzu
 settings:
   network:
     cni:
       name: antrea
     services:
       cidrBlocks: ["198.51.100.0/12"] #Cannot overlap with Supervisor Cluster
     pods:
       cidrBlocks: ["192.0.2.0/16"] #Cannot overlap with Supervisor Cluster
   storage:
     defaultClass: tanzu
